export const TEAMS = [
  { id: "ARG", name: "Argentina", flag: "🇦🇷", group: "A", baseCount: 8420 },
  { id: "AUS", name: "Australia", flag: "🇦🇺", group: "B", baseCount: 1200 },
  { id: "BEL", name: "Belgium", flag: "🇧🇪", group: "C", baseCount: 3100 },
  { id: "BRA", name: "Brazil", flag: "🇧🇷", group: "D", baseCount: 7800 },
  { id: "CMR", name: "Cameroon", flag: "🇨🇲", group: "E", baseCount: 950 },
  { id: "CAN", name: "Canada", flag: "🇨🇦", group: "F", baseCount: 4200 },
  { id: "CHN", name: "China PR", flag: "🇨🇳", group: "G", baseCount: 2100 },
  { id: "COL", name: "Colombia", flag: "🇨🇴", group: "H", baseCount: 2800 },
  { id: "CRI", name: "Costa Rica", flag: "🇨🇷", group: "A", baseCount: 800 },
  { id: "CRO", name: "Croatia", flag: "🇭🇷", group: "B", baseCount: 2900 },
  { id: "DNK", name: "Denmark", flag: "🇩🇰", group: "C", baseCount: 1700 },
  { id: "ECU", name: "Ecuador", flag: "🇪🇨", group: "D", baseCount: 1100 },
  { id: "EGY", name: "Egypt", flag: "🇪🇬", group: "E", baseCount: 1500 },
  { id: "ENG", name: "England", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", group: "F", baseCount: 6500 },
  { id: "FRA", name: "France", flag: "🇫🇷", group: "G", baseCount: 7100 },
  { id: "DEU", name: "Germany", flag: "🇩🇪", group: "H", baseCount: 6800 },
  { id: "GHA", name: "Ghana", flag: "🇬🇭", group: "A", baseCount: 1050 },
  { id: "GRC", name: "Greece", flag: "🇬🇷", group: "B", baseCount: 1300 },
  { id: "HND", name: "Honduras", flag: "🇭🇳", group: "C", baseCount: 600 },
  { id: "HUN", name: "Hungary", flag: "🇭🇺", group: "D", baseCount: 850 },
  { id: "IDN", name: "Indonesia", flag: "🇮🇩", group: "E", baseCount: 2200 },
  { id: "IRN", name: "Iran", flag: "🇮🇷", group: "F", baseCount: 1150 },
  { id: "ISR", name: "Israel", flag: "🇮🇱", group: "G", baseCount: 700 },
  { id: "ITA", name: "Italy", flag: "🇮🇹", group: "H", baseCount: 5900 },
  { id: "JAM", name: "Jamaica", flag: "🇯🇲", group: "A", baseCount: 920 },
  { id: "JPN", name: "Japan", flag: "🇯🇵", group: "B", baseCount: 4500 },
  { id: "KAZ", name: "Kazakhstan", flag: "🇰🇿", group: "C", baseCount: 400 },
  { id: "KOR", name: "South Korea", flag: "🇰🇷", group: "D", baseCount: 3800 },
  { id: "MEX", name: "Mexico", flag: "🇲🇽", group: "E", baseCount: 5200 },
  { id: "MAR", name: "Morocco", flag: "🇲🇦", group: "F", baseCount: 3400 },
  { id: "NLD", name: "Netherlands", flag: "🇳🇱", group: "G", baseCount: 4100 },
  { id: "NZL", name: "New Zealand", flag: "🇳🇿", group: "H", baseCount: 650 },
  { id: "NGA", name: "Nigeria", flag: "🇳🇬", group: "A", baseCount: 1800 },
  { id: "NOR", name: "Norway", flag: "🇳🇴", group: "B", baseCount: 1400 },
  { id: "PAN", name: "Panama", flag: "🇵🇦", group: "C", baseCount: 550 },
  { id: "PRY", name: "Paraguay", flag: "🇵🇾", group: "D", baseCount: 880 },
  { id: "PER", name: "Peru", flag: "🇵🇪", group: "E", baseCount: 1250 },
  { id: "POL", name: "Poland", flag: "🇵🇱", group: "F", baseCount: 2300 },
  { id: "POR", name: "Portugal", flag: "🇵🇹", group: "G", baseCount: 4900 },
  { id: "ROU", name: "Romania", flag: "🇷🇴", group: "H", baseCount: 1000 },
  { id: "SAU", name: "Saudi Arabia", flag: "🇸🇦", group: "A", baseCount: 1600 },
  { id: "SEN", name: "Senegal", flag: "🇸🇳", group: "B", baseCount: 1350 },
  { id: "SRB", name: "Serbia", flag: "🇷🇸", group: "C", baseCount: 1450 },
  { id: "SVK", name: "Slovakia", flag: "🇸🇰", group: "D", baseCount: 750 },
  { id: "ESP", name: "Spain", flag: "🇪🇸", group: "E", baseCount: 6200 },
  { id: "CHE", name: "Switzerland", flag: "🇨🇭", group: "F", baseCount: 2600 },
  { id: "URY", name: "Uruguay", flag: "🇺🇾", group: "G", baseCount: 2100 },
  { id: "USA", name: "United States", flag: "🇺🇸", group: "H", baseCount: 6100 },
];
