export const TEAMS = [
  { id: "DZA", name: "Algeria",              flag: "🇩🇿", group: "A", baseCount: 0 },
  { id: "ARG", name: "Argentina",            flag: "🇦🇷", group: "A", baseCount: 0 },
  { id: "AUT", name: "Austria",              flag: "🇦🇹", group: "A", baseCount: 0 },
  { id: "AUS", name: "Australia",            flag: "🇦🇺", group: "A", baseCount: 0 },
  { id: "BEL", name: "Belgium",              flag: "🇧🇪", group: "B", baseCount: 0 },
  { id: "BIH", name: "Bosnia & Herzegovina", flag: "🇧🇦", group: "B", baseCount: 0 },
  { id: "BRA", name: "Brazil",               flag: "🇧🇷", group: "B", baseCount: 0 },
  { id: "CPV", name: "Cabo Verde",           flag: "🇨🇻", group: "B", baseCount: 0 },
  { id: "CAN", name: "Canada",               flag: "🇨🇦", group: "C", baseCount: 0 },
  { id: "COL", name: "Colombia",             flag: "🇨🇴", group: "C", baseCount: 0 },
  { id: "COD", name: "Congo DR",             flag: "🇨🇩", group: "C", baseCount: 0 },
  { id: "CIV", name: "Côte d'Ivoire",        flag: "🇨🇮", group: "C", baseCount: 0 },
  { id: "CRO", name: "Croatia",              flag: "🇭🇷", group: "D", baseCount: 0 },
  { id: "CZE", name: "Czechia",              flag: "🇨🇿", group: "D", baseCount: 0 },
  { id: "CUW", name: "Curaçao",              flag: "🇨🇼", group: "D", baseCount: 0 },
  { id: "ECU", name: "Ecuador",              flag: "🇪🇨", group: "D", baseCount: 0 },
  { id: "EGY", name: "Egypt",                flag: "🇪🇬", group: "E", baseCount: 0 },
  { id: "ENG", name: "England",              flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", group: "E", baseCount: 0 },
  { id: "FRA", name: "France",               flag: "🇫🇷", group: "E", baseCount: 0 },
  { id: "DEU", name: "Germany",              flag: "🇩🇪", group: "E", baseCount: 0 },
  { id: "GHA", name: "Ghana",                flag: "🇬🇭", group: "F", baseCount: 0 },
  { id: "HTI", name: "Haiti",                flag: "🇭🇹", group: "F", baseCount: 0 },
  { id: "IRN", name: "IR Iran",              flag: "🇮🇷", group: "F", baseCount: 0 },
  { id: "IRQ", name: "Iraq",                 flag: "🇮🇶", group: "F", baseCount: 0 },
  { id: "JPN", name: "Japan",                flag: "🇯🇵", group: "G", baseCount: 0 },
  { id: "JOR", name: "Jordan",               flag: "🇯🇴", group: "G", baseCount: 0 },
  { id: "KOR", name: "Korea Republic",       flag: "🇰🇷", group: "G", baseCount: 0 },
  { id: "MEX", name: "Mexico",               flag: "🇲🇽", group: "G", baseCount: 0 },
  { id: "MAR", name: "Morocco",              flag: "🇲🇦", group: "H", baseCount: 0 },
  { id: "NLD", name: "Netherlands",          flag: "🇳🇱", group: "H", baseCount: 0 },
  { id: "NZL", name: "New Zealand",          flag: "🇳🇿", group: "H", baseCount: 0 },
  { id: "NOR", name: "Norway",               flag: "🇳🇴", group: "H", baseCount: 0 },
  { id: "PAN", name: "Panama",               flag: "🇵🇦", group: "I", baseCount: 0 },
  { id: "PRY", name: "Paraguay",             flag: "🇵🇾", group: "I", baseCount: 0 },
  { id: "POR", name: "Portugal",             flag: "🇵🇹", group: "I", baseCount: 0 },
  { id: "QAT", name: "Qatar",                flag: "🇶🇦", group: "I", baseCount: 0 },
  { id: "SAU", name: "Saudi Arabia",         flag: "🇸🇦", group: "J", baseCount: 0 },
  { id: "SCO", name: "Scotland",             flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", group: "J", baseCount: 0 },
  { id: "SEN", name: "Senegal",              flag: "🇸🇳", group: "J", baseCount: 0 },
  { id: "RSA", name: "South Africa",         flag: "🇿🇦", group: "J", baseCount: 0 },
  { id: "ESP", name: "Spain",                flag: "🇪🇸", group: "K", baseCount: 0 },
  { id: "SWE", name: "Sweden",               flag: "🇸🇪", group: "K", baseCount: 0 },
  { id: "CHE", name: "Switzerland",          flag: "🇨🇭", group: "K", baseCount: 0 },
  { id: "TUN", name: "Tunisia",              flag: "🇹🇳", group: "K", baseCount: 0 },
  { id: "TUR", name: "Türkiye",              flag: "🇹🇷", group: "L", baseCount: 0 },
  { id: "USA", name: "United States",        flag: "🇺🇸", group: "L", baseCount: 0 },
  { id: "URY", name: "Uruguay",              flag: "🇺🇾", group: "L", baseCount: 0 },
  { id: "UZB", name: "Uzbekistan",           flag: "🇺🇿", group: "L", baseCount: 0 },
];
